-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.ai_processing (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL,
  student_id uuid NOT NULL,
  file_url text,
  file_type character varying CHECK (file_type::text = ANY (ARRAY['pdf'::character varying, 'docx'::character varying, 'txt'::character varying, 'image'::character varying]::text[])),
  file_size bigint,
  text_content text,
  processing_status character varying DEFAULT 'pending'::character varying CHECK (processing_status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])),
  progress integer DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  result_sessions jsonb,
  error_message text,
  processing_time_seconds integer,
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  failed_at timestamp with time zone,
  CONSTRAINT ai_processing_pkey PRIMARY KEY (id),
  CONSTRAINT ai_processing_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.backups (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL,
  backup_type character varying NOT NULL CHECK (backup_type::text = ANY (ARRAY['manual'::character varying, 'auto'::character varying]::text[])),
  file_url text,
  file_size bigint,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  expires_at timestamp with time zone,
  CONSTRAINT backups_pkey PRIMARY KEY (id)
);
CREATE TABLE public.behavior_groups (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  code character varying NOT NULL UNIQUE,
  name_vn character varying NOT NULL,
  name_en character varying NOT NULL,
  description_vn text,
  description_en text,
  icon character varying,
  color_code character varying,
  common_tips jsonb,
  order_index integer NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT behavior_groups_pkey PRIMARY KEY (id)
);
CREATE TABLE public.behavior_incidents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_log_id uuid NOT NULL,
  behavior_library_id uuid,
  incident_number integer NOT NULL CHECK (incident_number > 0),
  antecedent text,
  behavior_description text NOT NULL,
  consequence text,
  duration_minutes integer CHECK (duration_minutes IS NULL OR duration_minutes > 0),
  intensity_level integer CHECK (intensity_level >= 1 AND intensity_level <= 5),
  frequency_count integer CHECK (frequency_count IS NULL OR frequency_count > 0),
  intervention_used text,
  intervention_effective boolean,
  environmental_factors text,
  occurred_at time without time zone NOT NULL,
  notes text,
  requires_followup boolean DEFAULT false,
  recorded_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  witnessed_by text,
  CONSTRAINT behavior_incidents_pkey PRIMARY KEY (id),
  CONSTRAINT behavior_incidents_session_log_id_fkey FOREIGN KEY (session_log_id) REFERENCES public.session_logs(id),
  CONSTRAINT behavior_incidents_behavior_library_id_fkey FOREIGN KEY (behavior_library_id) REFERENCES public.behavior_library(id)
);
CREATE TABLE public.behavior_library (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  behavior_group_id uuid NOT NULL,
  behavior_code character varying NOT NULL UNIQUE,
  name_vn character varying NOT NULL,
  name_en character varying NOT NULL,
  icon character varying,
  keywords_vn jsonb,
  keywords_en jsonb,
  manifestation_vn text,
  manifestation_en text,
  age_range_min integer,
  age_range_max integer,
  explanation jsonb,
  solutions jsonb,
  prevention_strategies jsonb,
  sources jsonb,
  related_behaviors jsonb,
  is_active boolean DEFAULT true,
  usage_count integer DEFAULT 0,
  last_used_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT behavior_library_pkey PRIMARY KEY (id),
  CONSTRAINT behavior_library_behavior_group_id_fkey FOREIGN KEY (behavior_group_id) REFERENCES public.behavior_groups(id)
);
CREATE TABLE public.content_library (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid,
  code character varying UNIQUE,
  title character varying NOT NULL,
  domain character varying NOT NULL CHECK (domain::text = ANY (ARRAY['cognitive'::character varying, 'motor'::character varying, 'language'::character varying, 'social'::character varying, 'self_care'::character varying]::text[])),
  description text,
  target_age_min integer,
  target_age_max integer,
  difficulty_level character varying CHECK (difficulty_level::text = ANY (ARRAY['beginner'::character varying, 'intermediate'::character varying, 'advanced'::character varying]::text[])),
  default_goals jsonb,
  estimated_duration integer,
  is_template boolean DEFAULT true,
  is_public boolean DEFAULT false,
  usage_count integer DEFAULT 0,
  rating_avg numeric DEFAULT 0.00 CHECK (rating_avg >= 0::numeric AND rating_avg <= 5::numeric),
  rating_count integer DEFAULT 0,
  last_used_at timestamp with time zone,
  tags jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  instructions jsonb,
  tips jsonb,
  materials_needed jsonb,
  CONSTRAINT content_library_pkey PRIMARY KEY (id),
  CONSTRAINT content_library_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.goal_evaluations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_log_id uuid NOT NULL,
  content_goal_id uuid NOT NULL,
  status character varying NOT NULL CHECK (status::text = ANY (ARRAY['achieved'::character varying, 'partially_achieved'::character varying, 'not_achieved'::character varying, 'not_applicable'::character varying]::text[])),
  achievement_level integer CHECK (achievement_level >= 0 AND achievement_level <= 100),
  support_level character varying CHECK (support_level::text = ANY (ARRAY['independent'::character varying, 'minimal_prompt'::character varying, 'moderate_prompt'::character varying, 'substantial_prompt'::character varying, 'full_assistance'::character varying]::text[])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT goal_evaluations_pkey PRIMARY KEY (id),
  CONSTRAINT goal_evaluations_session_log_id_fkey FOREIGN KEY (session_log_id) REFERENCES public.session_logs(id),
  CONSTRAINT goal_evaluations_content_goal_id_fkey FOREIGN KEY (content_goal_id) REFERENCES public.session_content_goals(id)
);
CREATE TABLE public.media_attachments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_log_id uuid NOT NULL,
  media_type character varying NOT NULL CHECK (media_type::text = ANY (ARRAY['image'::character varying, 'video'::character varying, 'audio'::character varying]::text[])),
  url text NOT NULL,
  thumbnail_url text,
  filename character varying NOT NULL,
  file_size bigint NOT NULL,
  mime_type character varying NOT NULL,
  width integer,
  height integer,
  duration integer,
  caption text,
  uploaded_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT media_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT media_attachments_session_log_id_fkey FOREIGN KEY (session_log_id) REFERENCES public.session_logs(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['session_completed'::text, 'message'::text, 'report_ready'::text, 'behavior_incident'::text, 'schedule_change'::text, 'general'::text])),
  title text NOT NULL,
  message text NOT NULL,
  data jsonb,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  related_entity_type text CHECK (related_entity_type = ANY (ARRAY['student'::text, 'session'::text, 'message'::text, 'behavior_incident'::text, NULL::text])),
  related_entity_id uuid,
  action_url text,
  read_at timestamp with time zone,
  push_sent boolean DEFAULT false,
  push_sent_at timestamp with time zone,
  expires_at timestamp with time zone,
  deleted_at timestamp with time zone,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.parent_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  recipient_id uuid NOT NULL,
  subject text NOT NULL,
  message text NOT NULL,
  is_read boolean DEFAULT false,
  parent_thread_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  read_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  reply_to_message_id uuid,
  CONSTRAINT parent_messages_pkey PRIMARY KEY (id),
  CONSTRAINT parent_messages_reply_to_message_id_fkey FOREIGN KEY (reply_to_message_id) REFERENCES public.parent_messages(id),
  CONSTRAINT parent_messages_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT parent_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(id),
  CONSTRAINT parent_messages_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.profiles(id),
  CONSTRAINT parent_messages_parent_thread_id_fkey FOREIGN KEY (parent_thread_id) REFERENCES public.parent_messages(id)
);
CREATE TABLE public.profile_favorites (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL,
  behavior_library_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profile_favorites_pkey PRIMARY KEY (id),
  CONSTRAINT profile_favorites_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['teacher'::text, 'parent'::text])),
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text NOT NULL UNIQUE,
  phone text,
  avatar_url text,
  language text DEFAULT 'vi'::text,
  timezone text DEFAULT 'Asia/Ho_Chi_Minh'::text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  school text,
  occupation text,
  relationship_to_student text,
  emergency_contact text,
  address text,
  notes text,
  last_login_at timestamp with time zone,
  push_token text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.reports (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL,
  format character varying NOT NULL CHECK (format::text = ANY (ARRAY['pdf'::character varying, 'excel'::character varying]::text[])),
  report_type character varying NOT NULL CHECK (report_type::text = ANY (ARRAY['individual'::character varying, 'summary'::character varying]::text[])),
  student_id uuid,
  date_from date NOT NULL,
  date_to date NOT NULL,
  file_url text,
  file_size bigint,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  expires_at timestamp with time zone,
  CONSTRAINT reports_pkey PRIMARY KEY (id),
  CONSTRAINT reports_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.session_content_goals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_content_id uuid NOT NULL,
  description text NOT NULL,
  goal_type character varying NOT NULL CHECK (goal_type::text = ANY (ARRAY['knowledge'::character varying, 'skill'::character varying, 'behavior'::character varying]::text[])),
  is_primary boolean DEFAULT false,
  order_index integer NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT session_content_goals_pkey PRIMARY KEY (id),
  CONSTRAINT session_content_goals_session_content_id_fkey FOREIGN KEY (session_content_id) REFERENCES public.session_contents(id)
);
CREATE TABLE public.session_contents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_id uuid NOT NULL,
  content_library_id uuid,
  title character varying NOT NULL,
  domain character varying NOT NULL CHECK (domain::text = ANY (ARRAY['cognitive'::character varying, 'motor'::character varying, 'language'::character varying, 'social'::character varying, 'self_care'::character varying]::text[])),
  description text,
  materials_needed text,
  estimated_duration integer,
  instructions text,
  tips text,
  order_index integer NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_custom_content_id uuid,
  CONSTRAINT session_contents_pkey PRIMARY KEY (id),
  CONSTRAINT session_contents_content_library_id_fkey FOREIGN KEY (content_library_id) REFERENCES public.content_library(id),
  CONSTRAINT session_contents_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id),
  CONSTRAINT session_contents_user_custom_content_id_fkey FOREIGN KEY (user_custom_content_id) REFERENCES public.user_custom_content(id)
);
CREATE TABLE public.session_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_id uuid NOT NULL UNIQUE,
  logged_at timestamp with time zone DEFAULT now(),
  actual_start_time time without time zone,
  actual_end_time time without time zone,
  mood character varying CHECK (mood::text = ANY (ARRAY['very_difficult'::character varying, 'difficult'::character varying, 'normal'::character varying, 'good'::character varying, 'very_good'::character varying]::text[])),
  energy_level integer CHECK (energy_level >= 1 AND energy_level <= 5),
  cooperation_level integer CHECK (cooperation_level >= 1 AND cooperation_level <= 5),
  focus_level integer CHECK (focus_level >= 1 AND focus_level <= 5),
  independence_level integer CHECK (independence_level >= 1 AND independence_level <= 5),
  attitude_summary text,
  progress_notes text CHECK (char_length(progress_notes) <= 2000),
  challenges_faced text CHECK (char_length(challenges_faced) <= 2000),
  recommendations text CHECK (char_length(recommendations) <= 2000),
  teacher_notes_text text CHECK (char_length(teacher_notes_text) <= 2000),
  overall_rating integer CHECK (overall_rating >= 1 AND overall_rating <= 5),
  completed_at timestamp with time zone,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT session_logs_pkey PRIMARY KEY (id),
  CONSTRAINT session_logs_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id)
);
CREATE TABLE public.session_media (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_log_id uuid NOT NULL,
  media_type text NOT NULL CHECK (media_type = ANY (ARRAY['photo'::text, 'video'::text])),
  url text NOT NULL,
  caption text,
  uploaded_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT session_media_pkey PRIMARY KEY (id),
  CONSTRAINT session_media_session_log_id_fkey FOREIGN KEY (session_log_id) REFERENCES public.session_logs(id),
  CONSTRAINT session_media_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  student_id uuid NOT NULL,
  session_date date NOT NULL,
  time_slot character varying NOT NULL CHECK (time_slot::text = ANY (ARRAY['morning'::character varying, 'afternoon'::character varying, 'evening'::character varying]::text[])),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  duration_minutes integer DEFAULT (EXTRACT(epoch FROM (end_time - start_time)) / (60)::numeric),
  location character varying,
  notes text,
  creation_method character varying DEFAULT 'manual'::character varying CHECK (creation_method::text = ANY (ARRAY['manual'::character varying, 'ai'::character varying]::text[])),
  status character varying DEFAULT 'scheduled'::character varying CHECK (status::text = ANY (ARRAY['scheduled'::character varying::text, 'completed'::character varying::text, 'cancelled'::character varying::text])),
  has_evaluation boolean DEFAULT false,
  cancellation_reason text,
  cancelled_at timestamp with time zone,
  created_by uuid NOT NULL DEFAULT auth.uid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT sessions_pkey PRIMARY KEY (id),
  CONSTRAINT sessions_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.student_parents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  parent_id uuid,
  relationship text NOT NULL CHECK (relationship = ANY (ARRAY['mother'::text, 'father'::text, 'guardian'::text, 'other'::text])),
  is_primary boolean DEFAULT false,
  can_view_reports boolean DEFAULT true,
  can_receive_notifications boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  parent_email text,
  relationship_note text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['invited'::text, 'active'::text, 'revoked'::text])),
  permissions jsonb DEFAULT '{"can_view_media": true, "can_view_sessions": true, "can_message_teacher": true, "can_view_session_logs": true, "can_receive_notifications": true, "can_view_goal_evaluations": true, "can_view_behavior_incidents": false}'::jsonb,
  invited_by uuid,
  invited_at timestamp with time zone DEFAULT now(),
  activated_at timestamp with time zone,
  revoked_at timestamp with time zone,
  revoked_by uuid,
  revoked_reason text,
  deleted_at timestamp with time zone,
  CONSTRAINT student_parents_pkey PRIMARY KEY (id),
  CONSTRAINT student_parents_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.profiles(id),
  CONSTRAINT student_parents_revoked_by_fkey FOREIGN KEY (revoked_by) REFERENCES public.profiles(id),
  CONSTRAINT student_parents_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT student_parents_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.students (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  nickname character varying,
  date_of_birth date NOT NULL,
  gender character varying NOT NULL CHECK (gender::text = ANY (ARRAY['male'::character varying, 'female'::character varying, 'other'::character varying]::text[])),
  avatar_url text,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'paused'::character varying, 'archived'::character varying]::text[])),
  diagnosis text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT students_pkey PRIMARY KEY (id),
  CONSTRAINT students_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.template_ratings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  content_library_id uuid NOT NULL,
  profile_id uuid NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  review text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT template_ratings_pkey PRIMARY KEY (id),
  CONSTRAINT template_ratings_content_library_id_fkey FOREIGN KEY (content_library_id) REFERENCES public.content_library(id)
);
CREATE TABLE public.user_custom_content (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL,
  title character varying NOT NULL,
  domain character varying NOT NULL CHECK (domain::text = ANY (ARRAY['cognitive'::character varying::text, 'motor'::character varying::text, 'language'::character varying::text, 'social'::character varying::text, 'self_care'::character varying::text])),
  description text,
  estimated_duration integer CHECK (estimated_duration > 0),
  default_goals jsonb DEFAULT '[]'::jsonb,
  tags jsonb DEFAULT '[]'::jsonb,
  usage_count integer DEFAULT 0 CHECK (usage_count >= 0),
  last_used_at timestamp with time zone,
  is_favorite boolean DEFAULT false,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  instructions jsonb,
  tips jsonb,
  materials_needed jsonb,
  CONSTRAINT user_custom_content_pkey PRIMARY KEY (id),
  CONSTRAINT user_custom_content_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);